/**
 * A Customer that has the ability to request orders. A Customer
 * consists of a name, phone number, email address, and unique ID
 * that is generated by the database.
 */
public class Customer {

    private String firstName;
    private String lastName;
    private String fullName;
    private String phone;
    private String email;
    private String notes;
    private int id;
    private boolean delinquent;

    /**
     * Constructor. Assigns the values provided to their associated fields.
     * @param firstName First name of the customer
     * @param lastName Last name of the customer
     * @param phone phone number of the customer
     * @param email Email address of the customer
     * @param notes Notes for the customer
     */
    public Customer(String firstName, String lastName, String phone, String email, String notes) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.email = email;
        this.notes = notes;
        this.fullName = lastName + ", " + firstName;
        this.delinquent = false;
    }

    /**
     * Constructor. Assigns the values provided to their associated fields.
     * @param id ID of the customer, assigned by the database
     * @param firstName First name of the customer
     * @param lastName Last name of the customer
     * @param phone phone number of the customer
     * @param email Email address of the customer
     * @param notes notes for the customer
     */
    public Customer(int id, String firstName, String lastName, String phone, String email, String notes) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phone = phone;
        this.email = email;
        this.notes = notes;
        this.fullName = lastName + ", " + firstName;
        this.delinquent = false;
    }

    /**
     * Gets the full name of the customer
     * @return The customer's full name
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the full name of the customer in Last, First notation
     * @param firstName First name of the customer
     * @param lastName Last name of the customer
     */
    public void setFullName(String firstName, String lastName) {
        this.fullName = lastName + ", " + firstName;
    }

    /**
     * Gets the first name of the Customer
     * @return The customer's first name
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the first name of the Customer
     * @param firstName The customer's first name
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Gets the last name of the Customer
     * @return The customer's last name
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the last name of the Customer
     * @param lastName The customer's last name
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Gets the phone number of the customer
     * @return The customer's phone number
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the Phone number of the Customer
     * @param phone The customer's phone number
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Gets the email address of the Customer
     * @return The customer's email address
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of the customer
     * @param email The customer's email address
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the notes for the Customer
     * @return The customer's notes
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the email address of the customer
     * @param email The customer's email address
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * Gets the ID for this customer
     * @return The customer's ID
     */
    public int getId() {
        return id;
    }
        
    /**
     * Gets the delinquent status of the customer
     * @return boolean "delinquent"
     */
    public boolean getDelinquent()
    {
        return delinquent;
    }

    /**
     * Sets the delinquent status of the cusotmer.
     * @param customerSucks whether the customer sucks or not
     */
    public void setDelinquent(boolean customerSucks)
    {
        delinquent = customerSucks;
    }
}
